version: "2.2"
services:
  jobmanager:
    image: pyflink-ocr:1.14.4
    ports:
      - "8081:8081"
    command: standalone-job -py /opt/flink/usrlib/main.py
    volumes:
      - ./:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - OMP_THREAD_LIMIT=1

  taskmanager:
    image: pyflink-ocr:1.14.4
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    volumes:
      - ./:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
      - OMP_THREAD_LIMIT=1
